apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: productsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsapi	  
  template:
    metadata:
      labels:
        app: productsapi
    spec:
      containers:
      - name: webapivaluesservice
        image: acrdevopsdemoproducts.azurecr.io/azuredevopscontainerimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: devopsdemoacesecret
---
apiVersion: v1
kind: Service
metadata:
  name: productsapiservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: productsapi